with open('src/App.jsx', 'r') as f:
    content = f.read()

# ── ADD SET 4 BUSINESSES ──────────────────────────────────────
new_businesses = """
  {
    id: 41,
    name: "M.D. Landscaping",
    category: "landscaping",
    city: "Victor Valley",
    phone: "(714) 360-8806",
    contact: "Chris / Will",
    address: "",
    email: "cwmdlandscaping@gmail.com",
    website: "",
    instagram: "@M.D._LAND_SCAPING",
    license: "",
    services: ["Weed Abatement", "Weed Prevention", "Rock Laying", "Trash Removal", "Tractor Work"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Landscaping services for the High Desert. Weed abatement, rock laying, trash removal, and tractor work. Serving the High Desert area.",
    initials: "MD",
    color: "#4A6B3C",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/mdlandscaping_front.png",
    cardBack: null,
  },
  {
    id: 42,
    name: "Midway City Remodeling",
    category: "contractors",
    city: "Victor Valley",
    phone: "(657) 705-5055",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Flooring", "Tile", "Drywall", "Texture", "Electrical", "Cabinets", "Paint"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Full-service remodeling for the High Desert. Flooring, tile, drywall, electrical, cabinets, and paint. Free estimates available.",
    initials: "MC",
    color: "#3C3C3C",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/midwaycityremodeling_front.png",
    cardBack: null,
  },
  {
    id: 43,
    name: "Pericos Party Rentals",
    category: "community",
    city: "Hesperia",
    phone: "(760) 949-2803",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Jumpers", "Boxing Rings", "Bouncers", "Water Slides", "Obstacle Courses", "Inflatable Pool", "Tables", "Chairs", "Party Heaters"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Family owned party rental business serving the High Desert since 2000. One of the biggest and most reliable inflatable rental companies in the area.",
    initials: "PP",
    color: "#D4824A",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/periscosparty_front.png",
    cardBack: null,
  },
  {
    id: 44,
    name: "Preferred Garage Doors",
    category: "contractors",
    city: "Victor Valley",
    phone: "(951) 535-1258",
    contact: "Adrian Gonzalez",
    address: "",
    email: "preferredfs.adrian@gmail.com",
    website: "",
    instagram: "",
    license: "",
    services: ["Garage Door Repair", "Spring Replacement", "Doors Off Track", "New Garage Doors", "Garage Door Installation"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Garage door specialist serving the High Desert since 2015. Specializing in spring changes and doors off track. Call Adrian for a free estimate.",
    initials: "PG",
    color: "#8B1A1A",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/prefferredgarage_front.png",
    cardBack: null,
  },
  {
    id: 45,
    name: "Rulis' Rentals",
    category: "community",
    city: "Victor Valley",
    phone: "(442) 469-9559",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@rulisrentals",
    license: "",
    services: ["Jumper/Slide Combo", "Double Water Slide", "Bounce Houses", "Party Rentals", "Weekday Specials"],
    hours: "Call or Text for hours",
    featured: false,
    tier: "free",
    description: "Party and inflatable rentals for the High Desert. Jumper/slide combos, water slides, and more. Weekday specials available.",
    initials: "RR",
    color: "#4A7A8F",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/rulisrentals_front.png",
    cardBack: null,
  },
  {
    id: 46,
    name: "Toro Remodeling LLC",
    category: "contractors",
    city: "Victor Valley",
    phone: "(909) 997-3748",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@tororemodeling llc",
    license: "Licensed, Bonded & Insured",
    services: ["Kitchen Remodels", "Bathroom Remodels", "Room Additions", "Full Home Renovations", "Outdoor Living Spaces"],
    hours: "Call for a Free Estimate",
    featured: false,
    tier: "free",
    description: "Licensed, bonded, and insured remodeling contractor for the High Desert. Kitchen, bathroom, room additions, and outdoor living spaces. Up to $500 off — call for a free estimate.",
    initials: "TR",
    color: "#C4603A",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/tororemodeling_front.png",
    cardBack: null,
  },
  {
    id: 47,
    name: "Velasco's Appliance Repair",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(760) 669-7254",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Appliance Repair", "Refrigerator Repair", "Washer Repair", "Dryer Repair", "Stove Repair", "Warranty Work"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional appliance repair serving the High Desert. All major brands including Whirlpool, Samsung, LG, GE, Bosch, and more. Works with warranty companies. Hablamos Español.",
    initials: "VA",
    color: "#E8A030",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/velascosappliance_front.png",
    cardBack: null,
  },
  {
    id: 48,
    name: "Appliances 4 Less",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(760) 927-8380",
    contact: "Carlos",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Appliance Sales", "Appliance Repair", "Refrigerators", "Stoves", "Washers", "Dryers"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Appliance sales and repairs for the High Desert. Refrigerators, stoves, washers, and dryers. Call Carlos for pricing.",
    initials: "AL",
    color: "#1B3A5C",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/appliance4less_front.png",
    cardBack: null,
  },
  {
    id: 49,
    name: "Black Horse Painting",
    category: "contractors",
    city: "Victor Valley",
    phone: "(951) 518-8404",
    contact: "",
    address: "",
    email: "",
    website: "blackhorsepainting.com",
    instagram: "@blackhorsepainting.com",
    license: "",
    services: ["Exterior Painting", "Interior Painting", "Cabinet Painting", "Drywall Repair"],
    hours: "Call for a Free Estimate",
    featured: false,
    tier: "free",
    description: "Professional painting services for the High Desert. Exterior, interior, cabinets, and drywall repair. Free estimates available.",
    initials: "BH",
    color: "#1B1B1B",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/blackhorsepainting_front.png",
    cardBack: null,
  },
  {
    id: 50,
    name: "Bounce Automotive Maintenance",
    category: "auto",
    city: "Victor Valley",
    phone: "(760) 490-5451",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@klvnbvng",
    license: "",
    services: ["Oil Changes", "Brake Changes", "Spark Plugs", "Serpentine Belt", "Steering and Suspension", "Diagnostics", "Mobile Services"],
    hours: "Call or Text for Appointment",
    featured: false,
    tier: "free",
    description: "Mobile automotive maintenance for the High Desert. Oil changes, brakes, spark plugs, diagnostics, and more. Mobile services available.",
    initials: "BA",
    color: "#3C3C3C",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/bouceautomeaint_front.png",
    cardBack: "/cards/bouceautomeaint_back.png",
  },
  {
    id: 51,
    name: "Carter's Garage Door",
    category: "contractors",
    city: "Victor Valley",
    phone: "(760) 514-5660",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Broken Springs", "Opener Repairs", "Door Repairs", "New Doors", "New Openers", "Garage Door Installation"],
    hours: "Call for a Free Estimate",
    featured: false,
    tier: "free",
    description: "Family owned garage door repair and installation for the High Desert. American workmanship — jobs done right. Free estimates available.",
    initials: "CG",
    color: "#1B3A5C",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/cartersgarage_front.png",
    cardBack: null,
  },
  {
    id: 52,
    name: "Desert Heat Yard Clean-Up",
    category: "landscaping",
    city: "Victor Valley",
    phone: "(760) 998-7315",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Tree Removal", "Tree Trimming", "Bush Removal", "Bush Trimming", "Rockscape", "Landscaping", "Junk Haul Away", "Weed Abatement", "Firewood"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Full yard cleanup and landscaping services proudly serving the entire High Desert. Tree removal, rockscape, weed abatement, and more.",
    initials: "DH",
    color: "#6B8F3C",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/desertheatyard_front.png",
    cardBack: null,
  },
  {
    id: 53,
    name: "HD Stars and Stripes",
    category: "landscaping",
    city: "Hesperia",
    phone: "(760) 782-2455",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Weed Abatement", "Brush & Land Clearing", "Gravel Install", "Junk & Debris Removal", "Yard Touch Up", "Monthly Subscriptions", "Weed Spraying", "Tree Trimming"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Yard and land services based in Hesperia. Weed abatement, brush clearing, gravel install, and monthly maintenance subscriptions available.",
    initials: "HS",
    color: "#4A6B3C",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/hdstarsandstripes_front.png",
    cardBack: null,
  },
  {
    id: 54,
    name: "Mr. G's Headlight Restoration",
    category: "auto",
    city: "Victor Valley",
    phone: "(909) 571-8065",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@mr.gs_headlight_restoration511",
    license: "",
    services: ["Headlight Restoration", "Foggy Headlight Repair", "Oxidized Headlight Repair"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional headlight restoration for the High Desert. Foggy, yellow, and oxidized headlights restored. Bilingual — servicio disponible en Español.",
    initials: "MG",
    color: "#8B1A1A",
    verified: true,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/headlighrestoration_front.png",
    cardBack: null,
  },
"""

# Insert before closing ];
last = content.rfind('\n];')
content = content[:last] + new_businesses + '\n];' + content[last+3:]
print('All 14 Set 4 businesses added!')

# ── CHECK & FIX EXISTING LICENSE NUMBERS ─────────────────────
license_fixes = [
    # (business name snippet, old license, new license)
    ('"Agape Pest Control"', 'license: ""', 'license: "OPR1460B"'),
    ('"Fence-MD"', 'license: ""', 'license: "CSLB #1142830"'),
    ('"SoCal Pest Pros"', 'license: ""', 'license: "OPR 13823"'),
    ('"High Desert General Construction"', 'license: ""', 'license: "CSLB #1077588"'),
]

for biz, old_lic, new_lic in license_fixes:
    if biz in content:
        # Find the business block and fix license within it
        idx = content.find(biz)
        block_end = content.find('cardBack:', idx)
        block = content[idx:block_end]
        if old_lic in block:
            new_block = block.replace(old_lic, new_lic, 1)
            content = content[:idx] + new_block + content[idx+len(block):]
            print(f'Fixed license for {biz}: {new_lic}')

with open('src/App.jsx', 'w') as f:
    f.write(content)
print('Done!')
