with open('src/App.jsx', 'r') as f:
    content = f.read()

new_businesses = """
  {
    id: 13,
    name: "Carlos Barber",
    category: "beauty",
    city: "Victor Valley",
    phone: "(760) 221-3339",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@cmjr.5",
    license: "",
    services: ["Haircuts", "Free Haircuts — Donations Appreciated"],
    hours: "Call to book",
    featured: false,
    tier: "free",
    description: "Local barber serving the High Desert. Free haircuts — donations appreciated. Scan QR code to book your appointment.",
    initials: "CB",
    color: "#1B3A5C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/carlosbarber-front.png",
    cardBack: null,
  },
  {
    id: 14,
    name: "Clean Bee & Co",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(442) 229-5522",
    contact: "",
    address: "",
    email: "CleanBeeofCa@Gmail.com",
    website: "",
    instagram: "@CleanBeeofCa",
    license: "",
    services: ["Standard Cleaning", "Deep Cleaning", "Move-In/Out Cleaning", "Eco-Friendly Cleaning"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional cleaning services for the High Desert. Eco-friendly, reliable, and detail oriented. Free quote available.",
    initials: "CB",
    color: "#6B8F71",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 1,
    carousel: false,
    cardFront: "/cards/cleanbeeco-front.png",
    cardBack: null,
  },
  {
    id: 15,
    name: "De La Torre Handyman",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(760) 601-0484",
    contact: "Alberto",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Painting", "Tree Trimming", "Palm Tree Trimming", "Garage Clean-Out", "Remodeling", "Plumbing", "Fences", "Lawn Maintenance", "Backyard Clean-Ups"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Full-service handyman for the High Desert. Bilingual — Español and English. Free estimates available. Call Alberto today.",
    initials: "DT",
    color: "#4A7A8F",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/delatorrehandyman-front.png",
    cardBack: "/cards/delatorrehandyman-back.png",
  },
  {
    id: 16,
    name: "Dog Waste Removal",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(909) 821-8427",
    contact: "Jack and Catherine McConnell",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Pet Waste Removal", "Dog Walking", "Dog Playing"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Local small business serving the High Desert community. Pet waste removal for $20 per visit. Dog walking and playing for $15 per hour.",
    initials: "DW",
    color: "#7A6B3C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 1,
    carousel: false,
    cardFront: "/cards/dogwasteremoval1-front.png",
    cardBack: null,
  },
  {
    id: 17,
    name: "Eliss Mariscos",
    category: "restaurants",
    city: "Victor Valley",
    phone: "",
    contact: "Elizabeth Gracian",
    address: "",
    email: "",
    website: "",
    instagram: "@ELISSMARISCOS",
    license: "",
    services: ["Shrimp Ceviche", "Mango Aguachile", "Catering Trays", "Jaz Tea"],
    hours: "Message on Instagram for availability",
    featured: false,
    tier: "free",
    description: "Fresh homemade mariscos in the High Desert. Shrimp ceviche, mango aguachile, and more. Message on Instagram for daily availability and orders.",
    initials: "EM",
    color: "#D4824A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 4,
    carousel: false,
    cardFront: "/cards/elissmariscos-front.png",
    cardBack: null,
  },
  {
    id: 18,
    name: "FreshStead Cleaning Service",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(760) 985-9716",
    contact: "Stephanie",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Residential Cleaning", "Commercial Cleaning", "Move-In/Move-Out", "Deep Clean", "Regular Maintenance"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional cleaning service for the High Desert. Contact Stephanie for a free quote. Residential, commercial, and move-in/out cleaning available.",
    initials: "FS",
    color: "#4A7A8F",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/freshsteadcleaning-front.png",
    cardBack: null,
  },
  {
    id: 19,
    name: "HD Pest Control",
    category: "contractors",
    city: "Phelan",
    phone: "(909) 538-9788",
    contact: "Guillermo Padilla",
    address: "PO Box 293875, Phelan, CA 92329",
    email: "Padilla909@gmail.com",
    website: "",
    instagram: "",
    license: "OPR# 14733 & PR# 9692",
    services: ["General Pest Control", "Roach Clean Out", "Actsol Treatment", "Bed Bugs", "Bees and Ants", "Rodent Control", "Aerial Roof Inspections"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Licensed, bonded, and insured pest control serving the High Desert and Inland Empire. Residential and commercial. Specializing in roach clean out and bed bugs.",
    initials: "HD",
    color: "#8B3A1A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/hdpestcontrol1-front.png",
    cardBack: null,
  },
  {
    id: 20,
    name: "HQE High Quality Epoxy Floors",
    category: "contractors",
    city: "Victor Valley",
    phone: "(714) 737-6394",
    contact: "Anthony F. & Jose D.",
    address: "",
    email: "HQE.FLOORING@YAHOO.COM",
    website: "",
    instagram: "",
    license: "",
    services: ["Metallic Finishes", "Marble Finishes", "Garage Floors", "Patio Floors", "Interior Floors", "Epoxy Flooring", "Flakes Available"],
    hours: "Call or Text for a Free Estimate",
    featured: false,
    tier: "free",
    description: "Premium epoxy flooring for garages, patios, and interior floors. Metallic and marble finishes available. Serving SoCal — quality you can trust.",
    initials: "HQ",
    color: "#E8A030",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/hqeflooring-front.png",
    cardBack: null,
  },
  {
    id: 21,
    name: "M.A.G.Z. Welding Mobile Services",
    category: "contractors",
    city: "Victor Valley",
    phone: "(951) 306-4323",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@magz.welding",
    license: "",
    services: ["Welding Repairs", "Reinforcement", "Fence Repair", "Trailer Welding", "Dump Trailer Welding", "Heavy Equipment Welding"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Mobile welding services for the High Desert. Specializing in welding repairs, reinforcement, fence repair, trailers, and heavy equipment.",
    initials: "MW",
    color: "#3C3C3C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 1,
    carousel: false,
    cardFront: "/cards/magzwelding-front.png",
    cardBack: "/cards/magzwelding-back.png",
  },
  {
    id: 22,
    name: "Ortiz Welding",
    category: "contractors",
    city: "Victor Valley",
    phone: "(714) 409-7276",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Mild Steel Welding", "Stainless Steel", "Aluminum", "Fabrication", "Modifications", "Reinforcements", "Repairs", "Gates", "Custom Doors"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional welding services for the High Desert. Mild steel, stainless, and aluminum. Fabrication, modifications, reinforcements, repairs, and custom gates. Bilingual — Español available.",
    initials: "OW",
    color: "#1B3A5C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/ortizwelding-front.png",
    cardBack: "/cards/ortizwelding-back.png",
  },
  {
    id: 23,
    name: "Sherwood Handyman Services",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(760) 596-9227",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Light Plumbing", "Painting", "Carpentry", "Drywall Repair", "Ceramic Tile", "Light Fixtures", "Fence Repair", "Electrical Outlet Replacement", "Linoleum Floors", "Bathroom Remodeling"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Reliable handyman services throughout the High Desert. From plumbing to bathroom remodeling — no job too small. Call for a free estimate.",
    initials: "SH",
    color: "#1B3A5C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/sherwoodhandyman-front.png",
    cardBack: null,
  },
  {
    id: 24,
    name: "SoCalHi Driving Lessons",
    category: "auto",
    city: "Victor Valley",
    phone: "(760) 780-3454",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Behind-the-Wheel Training", "Driver's Education Certification", "Vehicle Rental for DMV Testing", "Teen Driver Training"],
    hours: "Call or Text for hours",
    featured: false,
    tier: "free",
    description: "State certified driving instruction serving the High Desert. Behind-the-wheel training, driver's ed certification, and DMV vehicle rental. Bilingual — servicio disponible en Español.",
    initials: "SD",
    color: "#0D1B2A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/socalhidrivinglessons-front.png",
    cardBack: null,
  },
  {
    id: 25,
    name: "Steam Carpet Cleaning",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(760) 596-7419",
    textNumber: "(323) 667-5365",
    contact: "",
    address: "",
    email: "",
    website: "onewaycarpetcleaning.com",
    instagram: "",
    license: "",
    services: ["Carpet Cleaning", "Tile & Grout Cleaning", "Laminate Floor Cleaning", "Janitorial Service", "Move-In/Move-Out Cleaning"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional steam carpet cleaning for apartments, houses, and commercial properties throughout the High Desert. Tile, grout, and laminate floor cleaning also available.",
    initials: "SC",
    color: "#4A7A8F",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 1,
    carousel: false,
    cardFront: "/cards/steamcarpetcleaning1-front.png",
    cardBack: "/cards/steamcarpetcleaning1-back.png",
  },
  {
    id: 26,
    name: "The Party Pooper Scoopers LLC",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(909) 656-7790",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@thepartypooperscoopers.llc",
    license: "",
    services: ["Pet Waste Removal", "Weekly Service", "Free Quote Available"],
    hours: "Call or Text for hours",
    featured: false,
    tier: "free",
    description: "Professional pet waste removal starting at $23.75 per week. Serving the High Desert community. Call or text for a free quote today.",
    initials: "PP",
    color: "#6B8F71",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/thepartypooperscoopers-front.png",
    cardBack: null,
  },
"""

# Find the last business entry and insert after it
old = """    cardFront: "/cards/virginias-water-front.png",
    cardBack: null,
  },
];"""

new = """    cardFront: "/cards/virginias-water-front.png",
    cardBack: null,
  },""" + new_businesses + """
];"""

if old in content:
    content = content.replace(old, new)
    print('All 14 businesses added successfully!')
else:
    print('Could not find insertion point - checking alternate...')
    # Try alternate ending
    old2 = '    cardBack: null,\n  },\n];'
    if old2 in content:
        # Find the last occurrence
        last_pos = content.rfind(old2)
        content = content[:last_pos] + '    cardBack: null,\n  },' + new_businesses + '\n];' + content[last_pos + len(old2):]
        print('Added using alternate method!')
    else:
        print('ERROR: Could not find insertion point')

with open('src/App.jsx', 'w') as f:
    f.write(content)
