with open('src/App.jsx', 'r') as f:
    content = f.read()

new_businesses = """
  {
    id: 29,
    name: "Blank Slate Cleaning Co",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(323) 207-5311",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Residential Cleaning", "Office Cleaning", "Organizing"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional cleaning and organizing services for the High Desert. Residential, offices, and organizing. Call for a free quote.",
    initials: "BS",
    color: "#4A7A8F",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 1,
    carousel: false,
    cardFront: "/cards/blankslateclean_front.png",
    cardBack: null,
  },
  {
    id: 30,
    name: "C.A.R.S. Body Shop",
    category: "auto",
    city: "Hesperia",
    phone: "(760) 948-5151",
    contact: "",
    address: "9625 Tamarisk Ave, Hesperia, CA 92345",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Collision Repair", "Auto Body", "Paint Work", "Insurance Claims", "Free Rental", "Free Towing", "Lifetime Paint Warranty"],
    hours: "Mon–Fri 8:00 AM – 5:00 PM",
    featured: false,
    tier: "free",
    description: "Collision Auto Repair Specialists serving Hesperia. Insurance claim experts with lifetime paint warranty. Free towing and rental. Discounts for military, police, firefighters, and educators.",
    initials: "CA",
    color: "#8B3A1A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/carsautorepair_front.png",
    cardBack: null,
  },
  {
    id: 31,
    name: "Catalan's Landscaping",
    category: "landscaping",
    city: "Victor Valley",
    phone: "(714) 270-5579",
    contact: "",
    address: "",
    email: "bcatalan133@gmail.com",
    website: "",
    instagram: "",
    license: "",
    services: ["Maintenance", "Clean Ups", "Irrigation Systems", "Gardening", "Planting", "Removing", "Sprinklers", "Tree Trimming", "New Sod"],
    hours: "Call or Text for hours",
    featured: false,
    tier: "free",
    description: "Full-service landscaping for the High Desert. Residential and commercial. Free estimates available. Call or text for a quote.",
    initials: "CL",
    color: "#4A6B3C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/catalanslandscaping_front.png",
    cardBack: null,
  },
  {
    id: 32,
    name: "Cleaning Services Claudia",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(951) 460-9021",
    contact: "Claudia",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["House Cleaning", "Office Cleaning", "Deep Cleaning", "Move-In/Move-Out Cleaning"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Professional cleaning services for the High Desert. Houses, offices, deep cleaning, and move-in/move-out. Reasonable prices, professional and prompt.",
    initials: "CC",
    color: "#B85C8A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 1,
    carousel: false,
    cardFront: "/cards/cleaningservicesclaudia_front.png",
    cardBack: null,
  },
  {
    id: 33,
    name: "Misión Cristiana El Calvario",
    category: "community",
    city: "Hesperia",
    phone: "(760) 662-0961",
    textNumber: "(760) 557-5598",
    contact: "",
    address: "9980 Hesperia Rd, Hesperia, CA 92345",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Sunday Service 5PM", "Tuesday Service 7PM", "Friday Service 7PM", "Family Services"],
    hours: "Tue & Fri 7PM · Sun 5PM",
    featured: false,
    tier: "free",
    description: "A Christian family church serving the High Desert community in Hesperia. Services in Spanish. All are welcome.",
    initials: "EC",
    color: "#5C6B4A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/cristianaelcalvario_front.png",
    cardBack: null,
  },
  {
    id: 34,
    name: "Dollens Auto Repair LLC",
    category: "auto",
    city: "Victor Valley",
    phone: "(323) 986-0105",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "LIC #300249",
    services: ["Mobile Mechanic", "Auto Repairs", "Engine Repairs", "Diagnostics"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Licensed mobile mechanic serving the High Desert since 2021. We come to you — repairs done right. Call for an appointment.",
    initials: "DA",
    color: "#3C3C3C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/dollensautorepair_front.png",
    cardBack: null,
  },
  {
    id: 35,
    name: "Five Pillars Cleaning & Facility Services",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(442) 218-9763",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Residential Cleaning", "Deep Vacuum Service", "Junk Hauling", "Yard Cleanup", "Full Property Cleanup"],
    hours: "Call or Text for a Quote",
    featured: false,
    tier: "free",
    description: "Licensed and insured full property cleanup for the High Desert. One service for complete cleanup — residential cleaning, junk hauling, and yard cleanup.",
    initials: "FP",
    color: "#7A4A6B",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/fivepillarscleaning_front.png",
    cardBack: null,
  },
  {
    id: 36,
    name: "JC's Landscaping LLC",
    category: "landscaping",
    city: "Victor Valley",
    phone: "(840) 877-6522",
    contact: "Joey",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Weekly Maintenance", "Yard Clean-Ups", "Trash Hauling", "Tree Trimming", "Tree Removal", "Stump Grinding", "Vinyl & Wood Fencing", "Roofing", "Sod", "Sprinklers", "Tractor Work", "Rock Design", "Retaining Walls", "Artificial Turf", "Cement Slabs", "Patios", "Pavers", "Fire Prevention Clean Ups", "Snow Removal"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Full-service landscaping and property services for the High Desert. Making visions come to life. Senior citizen discounts available. Free estimates — call Joey.",
    initials: "JC",
    color: "#4A6B3C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 3,
    carousel: false,
    cardFront: "/cards/jcslandscaping_front.png",
    cardBack: null,
  },
  {
    id: 37,
    name: "Lexair HVAC",
    category: "homeservices",
    city: "Victor Valley",
    phone: "(760) 910-3732",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "LIC# 1127561",
    services: ["Air Conditioning", "Heating", "Swamp Coolers", "Mini Splits", "Central Heating & Cooling", "Air Duct Repair & Replace", "Maintenance & Tune-Ups", "24/7 Emergency Services", "Custom Home Installations", "Free Visual Inspections"],
    hours: "24/7 Emergency Available",
    featured: false,
    tier: "free",
    description: "Family owned and operated HVAC company with 20 years of experience serving the High Desert. Air conditioning, heating, swamp coolers, and emergency services available 24/7.",
    initials: "LA",
    color: "#1B3A5C",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 4,
    carousel: false,
    cardFront: "/cards/lexair_front.png",
    cardBack: "/cards/lexair_back.png",
  },
  {
    id: 38,
    name: "Raíz Limpia Lice Removal",
    category: "health",
    city: "Victor Valley",
    phone: "(951) 733-4564",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "@raizlimpia_liceremoval",
    license: "",
    services: ["Lice Removal", "Non-Toxic Treatment", "Free Head Checks", "Same Day Appointments", "After Hours Availability", "Mobile Service"],
    hours: "Same Day & After Hours Available",
    featured: false,
    tier: "free",
    description: "Mobile and non-toxic lice removal serving the Inland Empire and High Desert. Flat rate $150 full treatment. Free head checks for up to 3 family members. Same day appointments available.",
    initials: "RL",
    color: "#6B8F71",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 2,
    carousel: false,
    cardFront: "/cards/liceremovalraiz_front.png",
    cardBack: "/cards/liceremovalraiz_back.png",
  },
  {
    id: 39,
    name: "Reliable Junk Removal",
    category: "contractors",
    city: "Victor Valley",
    phone: "(760) 607-6938",
    contact: "",
    address: "",
    email: "",
    website: "",
    instagram: "",
    license: "",
    services: ["Dumpster Rental", "Tractor Work", "Junk Hauling", "Rock Delivery"],
    hours: "Call for hours",
    featured: false,
    tier: "free",
    description: "Reliable junk removal and hauling services for the High Desert. Dumpster rental, tractor work, junk hauling, and rock delivery available.",
    initials: "RJ",
    color: "#C4603A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 1,
    carousel: false,
    cardFront: "/cards/reliablejunkremoval_front.png",
    cardBack: null,
  },
  {
    id: 40,
    name: "Riki Tiki's Indoor Playground",
    category: "community",
    city: "Apple Valley",
    phone: "(442) 292-2198",
    contact: "",
    address: "20783 Bear Valley Road, Suite A, Apple Valley, CA 92308",
    email: "",
    website: "rikitikisindoorplayground.com",
    instagram: "",
    license: "",
    services: ["Indoor Playground", "Birthday Parties", "Family Events", "Open Play"],
    hours: "Daily 10:00 AM – 7:00 PM",
    featured: false,
    tier: "free",
    description: "Apple Valley's indoor playground for children and families. Open daily for play, birthday parties, and special events. Creating treasured memories for the High Desert community.",
    initials: "RT",
    color: "#D4824A",
    verified: false,
    dateAdded: "April 2026",
    lastVerified: "April 2026",
    expiresOn: "July 2026",
    baseThumbsUp: 4,
    carousel: false,
    cardFront: "/cards/rikitiki_front.png",
    cardBack: "/cards/rikitiki_back.png",
  },
"""

# Insert before the closing ];
last = content.rfind('];')
content = content[:last] + new_businesses + '\n];' + content[last+2:]

with open('src/App.jsx', 'w') as f:
    f.write(content)

print('Done! 12 new businesses added from Cards Set 3.')
print('Total listings now: 40')
